static const char *autocompletion_list =
	"abs acos add_instant add_interval add_property alert Analysis Annotation append "
	"Array asin ask assert atan atan2 bark_to_hertz bind_to_sound bool Boolean break "
	"ceil char class clear clear_directory clear_layer close get_coef get_column_type compare "
	"Concordance connect contains continue cos count create_dialog create_directory "
	"create_layer create_progress_dialog create_signal Dataset DataTable debug dharma "
	"Directory disconnect Document downto dump_json duplicate_layer "
	"E Element else elsif emit emmeans emtrends ends_with eof erb_to_hertz exists exp "
	"false field filter find find_back first fit float Float floor foreach "
	"Function function genericize get get_annotation get_annotations get_base_name "
	"get_cell get_column get_concordance get_concordances get_config_path "
	"get_current_annotation get_current_directory get_current_sound "
	"get_dataset get_datasets get_directory get_end get_event_count get_event_end "
	"get_event_index get_event_start get_event_text get_extension get_formants "
	"get_full_path get_header get_input get_intensity get_layer_count get_layer_label "
	"get_mean_intensity get_mean_pitch get_metadata_directory get_os_name "
	"get_path_separator get_pitch get_plugin_directory get_plugin_resource "
	"get_plugin_version get_property get_script_directory get_selected_annotations "
	"get_selected_sounds get_selection_duration get_settings_directory get_sound "
	"get_sounds get_spectral_moments get_spectrum get_start get_temp_directory "
	"get_temp_name get_user_directory get_visible_channels get_window_duration "
	"group has_match hertz_to_bark hertz_to_erb hertz_to_mel hertz_to_semitones "
	"import info insert int Integer intersect is_directory is_document is_empty "
	"is_sorted join join_path json last launch_browser layer_has_instants left "
	"len List list_directory load load_json local log log10 log2 ltrim "
	"match max mel_to_hertz min Model Module nativize Note null Number "
	"Object ones open open_directory_dialog open_file_dialog open_files_dialog option "
	"pass PHI phon PI pop prepend print Query random read read_file read_line "
	"read_lines Regex remove remove_at remove_directory remove_events remove_file "
	"remove_first remove_interval remove_last remove_layer remove_path remove_property "
	"rename repeat replace replace_at replace_first replace_last "
	"report_formants report_intensity report_mean_formants report_mean_intensity "
	"report_mean_pitch report_pitch return reverse rewind right round rtrim "
	"sample save save_file_dialog Script seek semitones_to_hertz Set set_cell "
	"set_current_directory set_event_text set_layer_label shift shuffle sin slice "
	"sort sorted_find sorted_insert Sound Spectrum split split_extension sqrt "
	"SQRT2 starts_with step str String strip_extension subtract summarize super "
	"Table tan tell then this throw to_csv to_lower to_upper trim true type "
	"unite until update_progress_dialog view_text warning while write "
	"write_as_native write_as_textgrid write_line write_lines zeros mean std vrc sum";
