static const char *autocompletion_list =
	"abs acos add_column add_instant add_interval add_property alert Analysis and "
	"Annotation append Array as asin ask assert atan atan2 bark_to_hertz bind_to_sound "
	"Bookmark Boolean break cast catch ceil Channel char class clear clear_console "
	"clear_layer close collect_garbage compare concatenate_annotations "
	"concatenate_sounds Concordance const contains continue convert cos count debug "
	"connect create_dialog create_directory create_layer create_progress_dialog "
	"create_signal Dataset disconnect emit "
	"DataTable dharma Directory div do Document duplicate_annotation duplicate_layer E "
	"Element else elsif emmeans emtrends encoding end ends_with eof erb_to_hertz Error option "
	"evaluate exists exp extract_annotation_slice extract_layers extract_sound_slice "
	"false field File filter finally find find_back first fit Float floor for "
	"FormantQuery freeze from_json Function function genericize get_annotation "
	"get_annotations get_base_name get_cell get_coef get_column get_column_type "
	"get_concordance get_concordances get_config_path get_current_annotation "
	"get_current_directory get_current_sound get_dataset get_datasets get_directory "
	"get_event_count get_event_end get_event_index get_event_start get_event_text "
	"get_extension get_formants get_full_path get_header get_input get_intensity "
	"get_layer_count get_layer_label get_mean_intensity get_mean_pitch "
	"get_metadata_directory get_os_name get_path_separator get_pitch "
	"get_plugin_directory get_plugin_resource get_plugin_version get_property "
	"get_script_directory get_script_path get_selection_duration get_settings_directory "
	"get_sound get_sounds get_spectral_moments get_spectrum get_temp_directory "
	"get_temp_name get_user_directory get_visible_channels get_voice_report "
	"get_window_duration global group group_count group_end group_start groups "
	"hertz_to_bark hertz_to_erb hertz_to_mel hertz_to_semitones if import in info "
	"insert Integer IntensityQuery intersect is is_directory is_document is_empty "
	"is_sorted join join_path keys last launch_browser layer_has_instants left len List "
	"list_directory local log log10 log2 ltrim Match match max mean mel_to_hertz "
	"merge_annotations method min mod Model nativize ncol ndim new_annotation not Note "
	"nrow null Number Object ones open open_directory_dialog open_file open_file_dialog "
	"open_files_dialog or parallel_map pattern phon PI PitchQuery polish pop predict "
	"prepend print Prior PriorSpec Query random read read_file read_line read_lines "
	"receive ref Regex regex remove remove_at remove_directory remove_events "
	"remove_file remove_first remove_interval remove_last remove_layer remove_path "
	"remove_property rename repeat replace return reverse rewind right round rtrim "
	"sample save save_file_dialog Script seek semitones_to_hertz send Set set_beta_phi "
	"SIGNAL_ANNOTATION_IMPORTED SIGNAL_ANNOTATION_LOADED SIGNAL_DATASET_LOADED "
	"SIGNAL_PROJECT_LOADED SIGNAL_SCRIPT_LOADED SIGNAL_SOUND_IMPORTED SIGNAL_SOUND_LOADED "
	"set_cell set_current_directory set_event_text set_fixed set_layer_label set_lkj "
	"set_negbin_theta set_residual set_variance shift shuffle sin slice sort "
	"sorted_find sorted_insert Sound spawn SpectralMomentsQuery Spectrum split "
	"split_extension sqrt starts_with std step String strip_extension subtract sum "
	"summarize Table tan tell then this throw TimeStamp to to_csv to_float to_int "
	"to_json to_lower to_string to_upper trim true try try_phase2 unite until "
	"update_progress_dialog values var view_text VoiceQualityQuery vrc wait warning "
	"while write write_as_native write_as_textgrid write_line write_lines zeros";
