# =====================================================================
# gen_reference_gaussian.R — Gaussian Bayesian reference (brms HMC).
#
# Mirrors frequentist/gen_reference_gaussian.R: same dataset
# (lme4::InstEval, 300-student subsample → inst_eval.csv), same five
# model formulas. Differences from the frequentist generator:
#
#   * Reference engine is brms (HMC) instead of glmmTMB (Laplace).
#   * Priors are explicit and match Phonometrica's auto-scaled
#     defaults bit-for-bit (see _helpers.R::phon_default_priors).
#   * The `0 + Intercept` formula trick exposes the raw intercept
#     so we can put N(mean(y), scale) on it directly.
#   * Reference summaries are posterior mean / sd / 95% CrI / pd
#     instead of estimate / SE.
#
# Five models:
#   M1 — y ~ studage * service                                 (no RE)
#   M2 — y ~ studage + lectage + service + (1|s)
#   M3 — y ~ studage + lectage + service + (1+service|s)       (random slope)
#   M4 — y ~ studage + lectage + service + (1|s) + (1|d)       (crossed)
#   M5 — y ~ studage + lectage + service + (1+service|s) + (1|d)
#
# Runtime: ~30-60 minutes on a 4-core machine for the full M1-M5
# sweep at default sampler settings (iter=4000, warmup=1000, 4 chains).
# Stan models are cached under stan_cache/, so re-runs after edits
# to data or priors recompile only when needed.
# =====================================================================

source("_helpers.R")

# inst_eval.csv is generated by frequentist/gen_reference_gaussian.R.
# We deliberately don't regenerate it here — both suites must read
# the same CSV so the comparison is apples-to-apples.
data_path <- resolve_data_path("inst_eval.csv")
if (!file.exists(data_path)) {
    stop(sprintf(
        "%s not found. Run frequentist/gen_reference_gaussian.R first to generate it.",
        data_path
    ))
}

d <- read.delim(data_path)   # tab-separated, matching frequentist suite convention
# Restore factor levels — read.delim returns characters by default.
d$studage <- factor(d$studage, levels = c("A2", "A4", "A6", "A8"))
d$lectage <- factor(d$lectage, levels = c("L1", "L2", "L3", "L4", "L5", "L6"))
d$service <- factor(d$service, levels = c("No", "Yes"))
d$s       <- factor(d$s)
d$d       <- factor(d$d)

# ── Fit and serialise ─────────────────────────────────────────────────
cat("Fitting M1 (lm-equivalent, no RE)...\n")
m1 <- fit_brms("y ~ studage * service", d, "gaussian", "gauss_M1")

cat("Fitting M2 (1|s)...\n")
m2 <- fit_brms("y ~ studage + lectage + service + (1|s)",
               d, "gaussian", "gauss_M2")

cat("Fitting M3 (1+service|s)...\n")
m3 <- fit_brms("y ~ studage + lectage + service + (1+service|s)",
               d, "gaussian", "gauss_M3")

cat("Fitting M4 (1|s) + (1|d)...\n")
m4 <- fit_brms("y ~ studage + lectage + service + (1|s) + (1|d)",
               d, "gaussian", "gauss_M4")

cat("Fitting M5 (1+service|s) + (1|d)...\n")
m5 <- fit_brms("y ~ studage + lectage + service + (1+service|s) + (1|d)",
               d, "gaussian", "gauss_M5")

models <- list(
    M1 = build_model_entry_brms(m1, "y ~ studage * service",                                       "gaussian"),
    M2 = build_model_entry_brms(m2, "y ~ studage + lectage + service + (1|s)",                    "gaussian"),
    M3 = build_model_entry_brms(m3, "y ~ studage + lectage + service + (1+service|s)",            "gaussian"),
    M4 = build_model_entry_brms(m4, "y ~ studage + lectage + service + (1|s) + (1|d)",            "gaussian"),
    M5 = build_model_entry_brms(m5, "y ~ studage + lectage + service + (1+service|s) + (1|d)",    "gaussian")
)

write_reference_brms(
    "gaussian", models, "inst_eval.csv",
    resolve_output_path("reference_gaussian.json")
)
cat("Done.\n")
